### ISSUE TITLE
Above view and side view meter setting showing yards

### ISSUE THREAD

**Issue by dmike2b** [schotime/schogolf#18]
Above view and side view meter setting showing yards. See attachment.
![knipsel](https://user-images.githubusercontent.com/46886487/52032969-85c6eb80-2523-11e9-8ecf-a0a79b0d335f.PNG)

**Comment by schotime** [comment]
That is not the distance of the shot but the scale. And coincidentally I chose to make the 110% of the largest shot, unless you are offline by more than 45m.
